/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Watchbot API
 * API documentation for Watchbot application
 * OpenAPI spec version: 1.0
 */

export * from './arrayResponseWrapper';
export * from './arrayResponseWrapperError';
export * from './bulkUpdateCollisionAlertSettingDto';
export * from './classTypeEo';
export * from './collisionAlertSettingDto';
export * from './collisionAlertSettingDtoSettingType';
export * from './createCollisionAlertSettingDto';
export * from './createCollisionAlertSettingDtoSettingType';
export * from './createEquipmentDto';
export * from './createUserDto';
export * from './equipmentDto';
export * from './equipmentsControllerFindAllParams';
export * from './equipmentsEntity';
export * from './fusionType';
export * from './getPresignedUrlDto';
export * from './getPresignedUrlDtoFileType';
export * from './imageDto';
export * from './loginDto';
export * from './loginDtoRole';
export * from './loginParamsDto';
export * from './nasOwnDto';
export * from './nasTargetDto';
export * from './nasTargetObjectDto';
export * from './nasTargetWebDto';
export * from './navigationStatus';
export * from './nmeaOwnDto';
export * from './nmeaTtmDto';
export * from './nmeaVdmDto';
export * from './ownshipDto';
export * from './radarTargetDto';
export * from './rPMDto';
export * from './rudderDto';
export * from './singleResponseWrapper';
export * from './singleResponseWrapperError';
export * from './socketDomDto';
export * from './socketDomDtoCamera';
export * from './socketDomDtoCore';
export * from './structureDto';
export * from './structureDtoType';
export * from './targetObjectDto';
export * from './targetObjectDtoClassTypeEo';
export * from './telegraphDto';
export * from './timeZoneDto';
export * from './updateCollisionAlertSettingDto';
export * from './updateEquipmentDto';
export * from './updateStructureDto';
export * from './updateStructureDtoEquipmentsItem';
export * from './updateStructureDtoType';
export * from './updateUserDto';
export * from './uploadResponseDto';
export * from './uploadResponseDtoFileType';
export * from './userDto';
export * from './vesselDto';
export * from './windReferenceType';
