/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Watchbot API
 * API documentation for Watchbot application
 * OpenAPI spec version: 1.0
 */

export * from './loginDto';
export * from './loginDtoRole';
export * from './loginParamsDto';
