/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Watchbot API
 * API documentation for Watchbot application
 * OpenAPI spec version: 1.0
 */

export type LoginDtoRole = (typeof LoginDtoRole)[keyof typeof LoginDtoRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoginDtoRole = {
  admin: 'admin',
  user: 'user',
} as const;
