/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Watchbot API
 * API documentation for Watchbot application
 * OpenAPI spec version: 1.0
 */

export interface LoginParamsDto {
  email: string;
  password: string;
}
