/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Watchbot API
 * API documentation for Watchbot application
 * OpenAPI spec version: 1.0
 */
import type { LoginDtoRole } from './loginDtoRole';

export interface LoginDto {
  fullName: string;
  accessToken: string;
  refreshToken: string;
  /** @nullable */
  expiresIn: number | null;
  role: LoginDtoRole;
}
