/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Watchbot API
 * API documentation for Watchbot application
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

/**
 * @summary Login
 */
export const authControllerLoginBodyEmailDefault = 'admin@example.com';
export const authControllerLoginBodyPasswordDefault = 'Admin@123';

export const authControllerLoginBody = zod.object({
  email: zod.string(),
  password: zod.string(),
});

export const authControllerLoginResponse = zod.object({
  fullName: zod.string(),
  accessToken: zod.string(),
  refreshToken: zod.string(),
  expiresIn: zod.number().nullable(),
  role: zod.enum(['admin', 'user']),
});
